name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          upstream-repository: https://github.com/Abstracta/jmeter-plugins.git
          forked-repository: https://github.com/Abstracta/jmeter-plugins.git
          plugin-artifact-name: jmeter-bzm-correlation-recorder
          plugin-id: bzm-siebel
          changes: some changes
          token: ${{ secrets.GH_TOKEN }}
          ignore-dependencies: bzm-repositories
        env:
          TEST_GITHUB_REPOSITORY: 'Blazemeter/CorrelationRecorder'

      - name: Print PR link
        run: echo "${{ steps.test-action.outputs.pull_request }}"

      - name: Delete PR
        run: gh pr close ${{ steps.test-action.outputs.pull_request }} --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
